'use strict';
/* BLOCK CITY TYCOON — one-command builds for every platform.
     npm run build:windows   → dist/windows/  BLOCK-CITY-TYCOON-Setup-<v>.exe, BLOCK-CITY-TYCOON-Portable-<v>.exe
     npm run build:android   → dist/android/  BLOCK-CITY-TYCOON-Android.apk (debug), BLOCK-CITY-TYCOON-Android-Release.apk
     npm run build:all       → both
   Build profiles (--profile=…): RELEASE (default — admin hidden, debug off, production UI, optimized),
   DEVELOPMENT (DevTools, debug panel, profiler without login), TEST (automated tests and performance tests).
   The profile is written to src/js/build-profile.js (git-ignored; a missing file means RELEASE).
   Android needs JDK 17+ and the Android SDK (ANDROID_HOME); the Gradle wrapper downloads Gradle on first use. */
const fs = require('fs'), path = require('path'), cp = require('child_process');
const ROOT = path.join(__dirname, '..');
const args = process.argv.slice(2);
const cmd = args.find(function (a) { return a.indexOf('--') !== 0; }) || 'help';
const profArg = (args.find(function (a) { return a.indexOf('--profile=') === 0; }) || '').split('=')[1];
const profile = ['development', 'test', 'release'].indexOf(profArg) >= 0 ? profArg : (cmd === 'profile' ? (args[1] || 'release') : 'release');
const pkg = require(path.join(ROOT, 'package.json'));

function writeProfile(target) {
  const o = { profile: profile, target: target, version: pkg.version, builtAt: new Date().toISOString() };
  fs.writeFileSync(PROFILE_FILE, "'use strict';\n/* GENERATED by scripts/build.js — build profile (missing file = RELEASE). */\nwindow.BCT_BUILD = " + JSON.stringify(o) + ';\n');
  console.log('✔ build profile ' + profile.toUpperCase() + ' (' + target + ')');
}
const PROFILE_FILE = path.join(ROOT, 'src', 'js', 'build-profile.js');
const PROFILE_DEFAULT = fs.existsSync(PROFILE_FILE) ? fs.readFileSync(PROFILE_FILE, 'utf8') : null;
function restoreProfile() { if (PROFILE_DEFAULT !== null) { fs.writeFileSync(PROFILE_FILE, PROFILE_DEFAULT); console.log('✔ build profile file restored'); } }
function run(bin, argv, opts) {
  console.log('> ' + bin + ' ' + argv.join(' '));
  const r = cp.spawnSync(bin, argv, Object.assign({ stdio: 'inherit', cwd: ROOT, shell: process.platform === 'win32' }, opts || {}));
  if (r.status !== 0) { console.error('✖ ' + bin + ' failed (exit ' + r.status + ')'); process.exit(r.status || 1); }
}
function copyDir(src, dst) {
  fs.rmSync(dst, { recursive: true, force: true }); fs.mkdirSync(dst, { recursive: true });
  fs.readdirSync(src, { withFileTypes: true }).forEach(function (e) {
    const s = path.join(src, e.name), d = path.join(dst, e.name);
    if (e.isDirectory()) copyDir(s, d); else fs.copyFileSync(s, d);
  });
}
function buildWindows() {
  writeProfile('windows');
  run(process.execPath, [path.join(ROOT, 'scripts', 'check.js')]);
  run(process.platform === 'win32' ? 'npx.cmd' : 'npx', ['electron-builder', '--win', 'nsis', 'portable', '--x64', '--publish', 'never']);
  restoreProfile();
  console.log('✔ Windows build → dist/windows/');
}
function buildAndroid() {
  writeProfile('android');
  const www = path.join(ROOT, 'android', 'app', 'src', 'main', 'assets', 'www');
  copyDir(path.join(ROOT, 'src'), www);                    // the same game files as the Windows EXE
  console.log('✔ game files copied to android/app/src/main/assets/www');
  restoreProfile();
  const gw = path.join(ROOT, 'android', process.platform === 'win32' ? 'gradlew.bat' : 'gradlew');
  const useWrapper = !process.env.BCT_GRADLE;
  run(useWrapper ? gw : process.env.BCT_GRADLE, ['-p', path.join(ROOT, 'android'), '--no-daemon', 'assembleDebug', 'assembleRelease'], { env: Object.assign({}, process.env, { BCT_PROFILE: profile }) });
  const out = path.join(ROOT, 'dist', 'android'); fs.mkdirSync(out, { recursive: true });
  [['debug', 'BLOCK-CITY-TYCOON-Android.apk'], ['release', 'BLOCK-CITY-TYCOON-Android-Release.apk']].forEach(function (x) {
    const f = path.join(ROOT, 'android', 'app', 'build', 'outputs', 'apk', x[0], x[1]);
    if (!fs.existsSync(f)) { console.error('✖ missing ' + f); process.exit(1); }
    fs.copyFileSync(f, path.join(out, x[1])); console.log('✔ dist/android/' + x[1] + ' (' + Math.round(fs.statSync(f).size / 1024) + ' KB)');
  });
}
switch (cmd) {
  case 'profile': writeProfile('local'); break;
  case 'windows': buildWindows(); break;
  case 'android': buildAndroid(); break;
  case 'all': buildWindows(); buildAndroid(); break;
  default: console.log('Usage: node scripts/build.js <windows|android|all|profile <development|test|release>> [--profile=release|test|development]');
}
